function init(self)
	self.dir = vmath.vector3(0, -1, 0)
	self.speed = 400
end

function update(self, dt)
	local pos = go.get_position()
	pos = pos + self.dir * self.speed * dt
	go.set_position(pos)
	local rotat = go.get_rotation()
	--print(rotat)
	local change = vmath.quat_rotation_z(3.14*dt)
	--print(rotat * change)
	go.set_rotation(rotat*change)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		go.delete()
	end
end