function init(self)
end

function final(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("createCloud") then
		local coords = message
		local initPOS = vmath.vector3(coords[1]*32, coords[2]*33.5, 1)
		go.set_position(initPOS, go.get_id())
	end
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
