local timer = 0
local trackplayer = false

function init(self)
	self.dir = vmath.vector3(0, 1, 0)
	self.speed = 100
	self.going = nil
	msg.post(".","get_new_position")
	timer = 0
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)

	local anim = hash("idle")

	if trackplayer then
		local current_position = go.get_position()
		local diff = go.get_position("/Player") - current_position
		local distance_to_target = vmath.length(diff)
		if distance_to_target > 0 then
			local direction = vmath.normalize(diff)
			-- don't overshoot the target by moving too far in a frame
			local distance_to_move = math.min(distance_to_target, self.speed * dt)
			-- update with the new position
			local new_position = current_position + direction * distance_to_move
			go.set_position(new_position)

			if new_position.y > current_position.y then
				anim = hash("up")
			elseif new_position.y < current_position.y then
				anim = hash("down")
			end

			if anim ~= self.current_anim then                          -- [3]
				msg.post("#sprite", "play_animation", { id = anim })   -- [4]
				self.current_anim = anim                               -- [5]
			end

		elseif distance_to_target <= 0 then
			anim = hash("idle")
		end
	else
		if timer == 0 then
			local current_position = go.get_position()
			local diff = self.going - current_position
			local distance_to_target = vmath.length(diff)
			if distance_to_target > 0 then
				local direction = vmath.normalize(diff)
				-- don't overshoot the target by moving too far in a frame
				local distance_to_move = math.min(distance_to_target, self.speed * dt)
				-- update with the new position
				local new_position = current_position + direction * distance_to_move
				go.set_position(new_position)

				if self.going.y > current_position.y then
					anim = hash("up")
				elseif self.going.y < current_position.y then
					anim = hash("down")
				end

				if anim ~= self.current_anim then                          -- [3]
					msg.post("#sprite", "play_animation", { id = anim })   -- [4]
					self.current_anim = anim                               -- [5]
				end

			elseif distance_to_target <= 0 then
				anim = hash("idle")
				timer = 60
			end
		elseif timer == 1 then
			msg.post(".","get_new_position")
			timer = timer -1
		else
			timer = timer - 1
		end
	end

end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("get_new_position") then
		local pos = go.get_position()
		pos.x = pos.x + math.random(-400,400)
		pos.y = pos.y + math.random(-400,400)
		self.going = pos
	elseif message_id == hash("collision_response") then
		if not trackplayer then
			trackplayer = true
		end
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
