-- Sets up the object to recieve the data from the factory.create call
go.property("anim", hash(""))

function init(self)
	-- Tells itself to play the right animation 
	msg.post(".", "play_animation", {id = self.anim})
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- When it recieves the animation done message it deletes itself
	if message_id == hash("animation_done") then
		go.delete()
	end
	-- When it recieves a collision response from it's trigger hitboxes
	--if message_id == hash("trigger_response") then
		-- Checks if the collision is with the proper side of the knife and deletes the other object if it's correct
		--if message.own_group == hash("up") and self.anim == hash("melee_up_sword") then
			--go.delete(message.other_id)
		--elseif message.own_group == hash("down") and self.anim == hash("melee_down_sword") then
			--go.delete(message.other_id)
		--elseif message.own_group == hash("left") and self.anim == hash("melee_left_sword") then
			--go.delete(message.other_id)
		--elseif message.own_group == hash("right") and self.anim == hash("melee_right_sword") then
			--go.delete(message.other_id)
		--end
	--send
	
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
